const PREFIX = 'md-reader__'
const p = ([block]: TemplateStringsArray) => PREFIX + block

export default {
  PREFIX,
  MD_BODY: p`body`,
  MD_SIDE: p`side`,
  MD_SIDE_ACTIVE: p`side-li--active`,
  MD_CONTENT: p`markdown-content`,
  MD_BUTTON: p`btn`,
  HEAD_ANCHOR: p`head-anchor`,
  BUTTON_WRAP_ELE: p`button-wrap`,
  CODE_TOGGLE_BTN: p`btn--code-toggle`,
  SIDE_EXPAND_BTN: p`btn--side-expand`,
  GO_TOP_BTN: p`btn--go-top`,
  COPY_BTN: p`btn--copy`,
  TTS_BTN: p`btn--tts`,
  TTS_PAUSE_BTN: p`btn--tts-pause`,
  TTS_STOP_BTN: p`btn--tts-stop`,
  TTS_SETTINGS_BTN: p`btn--tts-settings`,
  TTS_MODAL: p`tts-modal`,
  TTS_SENTENCE: p`tts-sentence`,
  FILE_NAV: p`file-nav`,
  FILE_NAV_TITLE: p`file-nav-title`,
  FILE_NAV_TOGGLE: p`file-nav-toggle`,
  FILE_NAV_LIST: p`file-nav-list`,
  FILE_NAV_ITEM: p`file-nav-item`,
  FILE_NAV_ITEM_ACTIVE: p`file-nav-item--active`,
  FILE_NAV_DIR: p`file-nav-dir`,
  SIDE_COLLAPSED: 'side-collapsed',
  SIDE_EXPANDED: 'side-expanded',
  MODAL: p`modal`,
  ZOOM_IMAGE: p`zoom-image`,
}
